export const seedData = {
  users: [
    {
      email: "sample@sample1.com",
      slug: "sample1",
      password: "sample1",
      name: "Sample User 1",
    },
  ],
  actions: [
    {
      name: "Idle",
      slug: "idle",
      icon: "🧘",
    },
    {
      name: "Run",
      slug: "run",
      icon: "🏃",
    },
    {
      name: "Walk",
      slug: "walk",
      icon: "🚶",
    },
    {
      name: "Jump",
      slug: "jump",
      icon: "🤾",
    },
    {
      name: "Rotate Horizontal",
      slug: "rotate_horizontal",
      icon: "↪️",
    },
    {
      name: "Rotate Vertical",
      slug: "rotate_vertical",
      icon: "↪️",
    },
    {
      name: "Walk",
      slug: "walk_2",
      icon: "🚶",
    },
    {
      name: "Jump to Idle",
      slug: "jump_to_idle",
      icon: "🤾⏩🧘",
    },
    {
      name: "Idle Hit React 2",
      slug: "idle_hit_react_2",
      icon: "🧘💥2️⃣",
    },
    {
      name: "Idle Hit React 1",
      slug: "idle_hit_react_1",
      icon: "🧘💥1️⃣",
    },
    {
      name: "Idle 2 Head Low",
      slug: "idle_2_head_low",
      icon: "🧘2️⃣👇",
    },
    {
      name: "Idle 2",
      slug: "idle_2",
      icon: "🧘2️⃣",
    },
    {
      name: "Gallop",
      slug: "gallop",
      icon: "🐎",
    },
    {
      name: "Idle",
      slug: "idle_2_duplicate",
      icon: "🧘",
    },
    {
      name: "Eating",
      slug: "eating",
      icon: "🍴",
    },
    {
      name: "Death",
      slug: "death",
      icon: "💀",
    },
    {
      name: "Attack",
      slug: "attack",
      icon: "⚔️",
    },
    {
      name: "Gallop Jump",
      slug: "gallop_jump",
      icon: "🐎🤾",
    },
  ],
  creators: [
    {
      name: "Yuri Nakanishi",
      slug: "YuriNakanishi",
      description: "Developer of Meshmell.",
      twitter: "https://twitter.com/yurimell6174",
      website: "https://yurimell.com/",
      roles: ["creator", "developer"],
    },
  ],
  categories: [
    {
      slug: "all",
      name: "All",
      icon: "🌎",
      color: "bg-emerald-500",
    },
    {
      slug: "suggested",
      name: "Suggested",
      icon: "🔥",
      color: "bg-emerald-500",
    },
    {
      slug: "animal",
      name: "Animal",
      icon: "🐶",
      color: "bg-emerald-500",
    },
    {
      slug: "furniture",
      name: "Furniture",
      icon: "🪑",
      color: "bg-emerald-500",
    },
    {
      slug: "nature",
      name: "Nature",
      icon: "🌳",
      color: "bg-emerald-500",
    },
    {
      slug: "food",
      name: "Food",
      icon: "🍔",
      color: "bg-emerald-500",
    },
    {
      slug: "weapon",
      name: "Weapon",
      icon: "🔫",
      color: "bg-emerald-500",
    },
    {
      slug: "lowPoly",
      name: "Low Poly",
      icon: "🟨",
      color: "bg-emerald-500",
    },
    {
      slug: "real",
      name: "Real",
      icon: "🟦",
      color: "bg-emerald-500",
    },
  ],
  models: [
    {
      slug: "animated_cube",
      resolutions: ["1k"],
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 1,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
      name: "Animated Cube",
      description: "",
      creator: "YuriNakanishi",
      published: "2024-01-02",
      updated: "2024-01-02",
      categoryTags: ["technology", "real"],
      price: 0,
      license: "CC0",
      credit: "",
      actions: ["rotate_horizontal", "rotate_vertical"],
      isDownloadable: true,
    },
    {
      slug: "sci-fi_worker_robot",
      resolutions: ["1k"],
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 0.3,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
      name: "Sci-Fi Worker Robot",
      description: "",
      creator: "YuriNakanishi",
      published: "2024-01-02",
      updated: "2024-01-02",
      categoryTags: ["technology", "real"],
      price: 0,
      license: "CC0",
      credit: "",
      isDownloadable: false,
      source: {
        creator: "RyanKingArt",
        sourceSite: "https://ryankingart.gumroad.com/l/kobsg?layout=profile",
        downloadSite: "https://ryankingart.gumroad.com/l/kobsg?layout=profile",
        sourceVideo: "https://www.youtube.com/watch?v=3zvz1z5t8zA",
      },
    },
    {
      slug: "potted_plant_01",
      resolutions: ["1k"],
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 5,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
      name: "Potted plant 01",
      description: "",
      creator: "RicoCilliers",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/potted_plant_01",
      isDownloadable: true,
    },
    {
      slug: "wooden_crate_01",
      resolutions: ["1k"],
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 5,
      rotationDegrees: {
        x: 0,
        y: -90,
        z: 0,
      },
      name: "Wooden Crate 01",
      description: "",
      creator: "JamesRayCock",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/wooden_crate_01",
      isDownloadable: true,
    },
    {
      slug: "wooden_table_02",
      resolutions: ["1k"],
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 4,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
      name: "Wooden Table 02",
      description: "",
      creator: "SerhiiKhromov",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/wooden_table_02",
      isDownloadable: true,
    },
    {
      slug: "food_apple_01",
      resolutions: ["1k"],
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 25,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
      name: "Food Apple 01",
      description: "",
      creator: "OliverHarries",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "food", "nature", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/food_apple_01",
      isDownloadable: true,
    },
    {
      slug: "fox_01",
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 1,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
      name: "Fox",
      description: "",
      creator: "Quaternius",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["nature", "animal", "lowPoly"],
      price: 0,
      license: "CC0",
      credit: "https://quaternius.com/packs/ultimateanimatedanimals.html",
      actions: [
        "Walk",
        "Jump_ToIdle",
        "Idle_HitReact2",
        "Idle_HitReact1",
        "Idle_2_HeadLow",
        "Idle_2",
        "Idle",
        "Gallop",
        "Eating",
        "Death",
        "Attack",
        "Gallop_Jump",
      ],
      isDownloadable: true,
    },
    {
      slug: "wicker_basket_01",
      resolutions: ["1k"],
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 12,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
      name: "Wicker Basket 01",
      description: "",
      creator: "KuuttiSiitonen",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/wicker_basket_01",
      isDownloadable: true,
    },
    {
      slug: "wooden_handle_saber",
      resolutions: ["1k"],
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 4,
      rotationDegrees: {
        x: 0,
        y: 90,
        z: 0,
      },
      name: "Wooden Handle Saber",
      description: "",
      creator: "UlanCabanilla",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["weapon", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/wooden_handle_saber",
      isDownloadable: true,
    },
    {
      slug: "wine_barrel_01",
      resolutions: ["1k"],
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 5,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
      name: "Wine Barrel 01",
      description: "",
      creator: "JamesRayCock",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/wine_barrel_01",
      isDownloadable: true,
    },
    {
      slug: "wolf_01",
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 1.2,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
      name: "Wolf",
      description: "",
      creator: "Quaternius",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "nature", "animal", "lowPoly"],
      price: 0,
      license: "CC0",
      credit: "https://quaternius.com/packs/ultimateanimatedanimals.html",
      actions: [
        "Walk",
        "Jump_ToIdle",
        "Idle_HitReact2",
        "Idle_HitReact1",
        "Idle_2_HeadLow",
        "Idle_2",
        "Idle",
        "Gallop",
        "Eating",
        "Death",
        "Attack",
        "Gallop_Jump",
      ],
      isDownloadable: true,
    },
    {
      slug: "book_encyclopedia_set_01",
      resolutions: ["1k"],
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 6,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
      name: "Book Encyclopedia Set 01",
      description: "",
      creator: "JohnMalcolm",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/book_encyclopedia_set_01",
      isDownloadable: true,
    },
    {
      slug: "round_wooden_table_01",
      resolutions: ["1k"],
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 3,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
      name: "Round Wooden Table 01",
      description: "",
      creator: "UlanCabanilla",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/round_wooden_table_01",
      isDownloadable: true,
    },
    {
      slug: "cardboard_box_01",
      resolutions: ["1k"],
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 8,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
      name: "Cardboard Box 01",
      description: "",
      creator: "RahulChaudhary",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/cardboard_box_01",
      isDownloadable: true,
    },
    {
      slug: "dining_chair_02",
      resolutions: ["1k"],
      formats: [{ name: "glb", isUsed: true }],
      usedFormat: "glb",
      scale: 5,
      rotationDegrees: {
        x: 0,
        y: 0,
        z: 0,
      },
      name: "Dining Chair 02",
      description: "",
      creator: "JamesRayCock",
      published: "2021-10-31",
      updated: "2021-10-31",
      categoryTags: ["suggested", "furniture", "real"],
      price: 0,
      license: "CC0",
      credit: "https://polyhaven.com/a/dining_chair_02",
      isDownloadable: true,
    },
  ],
};

export default seedData;
