export const seedDevData = {
  sponsors: [
    {
      name: "Async Corporation",
      slug: "async_corporation",
      description: "",
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 10000,
    },
    {
      name: "Francisco D'Anconia",
      slug: "francisco_danconia",
      description: "",
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 150000,
    },
    {
      name: "Kalinin and Associates",
      slug: "kalinin_and_associates",
      description: "",
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 1500,
    },
    {
      name: "Charles Williams",
      slug: "charles_williams",
      description: "",
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 1500,
    },
    {
      name: "Hiroki Kuroda",
      slug: "hiroki_kuroda",
      description: "",
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 1500,
    },
    {
      name: "Isla Roberts",
      slug: "isla_roberts",
      description: "",
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 1500,
    },
    {
      name: "Tracy Garcia",
      slug: "tracy_garcia",
      description: "",
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 1500000,
    },
    {
      name: "Susan Smith",
      slug: "susan_smith",
      description: "",
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 1500,
    },
    {
      name: "Gelbero.com",
      slug: "gelbero_com",
      description: "",
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 150000,
    },
    {
      name: "Michael 3D Printing",
      slug: "michael_3d_printing",
      description: "",
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 15000,
    },
    {
      name: "Margaret O'Brien",
      slug: "margaret_obrien",
      description: "",
      url: "https://example.com",
      published: "",
      updated: "",
      amount: 150,
    },
  ],
  creators: [
    {
      name: "Ryan King Art",
      slug: "RyanKingArt",
      description:
        "Ryan King Art is a 3D artist who creates 3D models and renders. He is also a YouTuber who shares his knowledge of 3D modeling and rendering.",
      twitter: "https://twitter.com/RyanKingArt",
      website: "https://www.ryankingart.com/",
      youtube: "https://www.youtube.com/channel/UCfjswDVU0XHyBN7UFG0Mi5Q",
      roles: ["creator"],
    },
    {
      name: "Rico Cilliers",
      slug: "RicoCilliers",
      description: "Technical Director at Polyhaven.com",
      artStation: "https://www.artstation.com/rico_b3d",
      roles: ["creator"],
    },
    {
      name: "Oliver Harries",
      slug: "OliverHarries",
      description: "Freelance 3D Artist.",
      website: "https://oliverharries.myportfolio.com/",
      roles: ["creator"],
    },
    {
      name: "Quaternius",
      slug: "Quaternius",
      description: "3D Artist.",
      website: "https://quaternius.com/",
      roles: ["creator"],
    },
    {
      name: "James Ray Cock",
      slug: "JamesRayCock",
      description: "3D Artist for Games and Film.",
      artStation: "https://www.artstation.com/jamesray",
      roles: ["creator"],
    },
    {
      name: "Serhii Khromov",
      slug: "SerhiiKhromov",
      description: "Material/Environment Artist.",
      artStation: "https://www.artstation.com/serhiikhromov",
      roles: ["creator"],
    },
    {
      name: "Rahul Chaudhary",
      slug: "RahulChaudhary",
      description: "3D Environment and Prop Artist.",
      artStation: "https://www.artstation.com/rc12",
      roles: ["creator"],
    },
    {
      name: "Kuutti Siitonen",
      slug: "KuuttiSiitonen",
      description: "3D Artist.",
      artStation: "https://www.artstation.com/KuuttiSiitonen",
      paypal: "https://www.paypal.com/paypalme/kuuttis",
      roles: ["creator"],
    },
    {
      name: "John Malcolm",
      slug: "JohnMalcolm",
      description: "",
      roles: ["creator"],
    },
    {
      name: "Ulan Cabanilla",
      slug: "UlanCabanilla",
      description: "",
      roles: ["creator"],
    },
  ],
};

export default seedDevData;
