name: Yurimell Next.js Cloud Run

# on:
#   push:
#     branches:
#       - develop
#       - main

on:
  push:
    branches:
      - aaa

env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  REGION: us-west1
  REPO_NAME: yurimell
  SERVICE_NAME: yurimell
  NEXT_PUBLIC_BASE_URL: "https://yurimell.com"
  NEXT_PUBLIC_GA_MEASUREMENT_ID: "GA-MEASUREMENT-ID"
  NEXT_PUBLIC_GCS_BUCKET_URL: "https://bucket-url"
  NEXT_PUBLIC_ARTICLES_NUMBER_BY_LIST_PAGE: 10
  NEXT_PUBLIC_RANDOM_SUGGESTED_ARTICLES_NUMBER_BY_DETAIL_PAGE: 5
  NEXT_PUBLIC_ENV_STATUS: "production"
  NEXT_PUBLIC_SUBDOMAIN_FOR_PRODUCTION: "subdomain.example.com"
  NEXT_PUBLIC_THOUGHTS_NUMBER_BY_LIST_PAGE: 10
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DIRECT_URL: ${{ secrets.DIRECT_URL }}

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build the Docker image
        run: |
          docker build \
            -t $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$SERVICE_NAME:$GITHUB_SHA \
            --build-arg NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL \
            --build-arg NEXT_PUBLIC_GA_MEASUREMENT_ID=$NEXT_PUBLIC_GA_MEASUREMENT_ID \
            --build-arg NEXT_PUBLIC_GCS_BUCKET_URL=$NEXT_PUBLIC_GCS_BUCKET_URL \
            --build-arg NEXT_PUBLIC_ARTICLES_NUMBER_BY_LIST_PAGE=$NEXT_PUBLIC_ARTICLES_NUMBER_BY_LIST_PAGE \
            --build-arg NEXT_PUBLIC_RANDOM_SUGGESTED_ARTICLES_NUMBER_BY_DETAIL_PAGE=$NEXT_PUBLIC_RANDOM_SUGGESTED_ARTICLES_NUMBER_BY_DETAIL_PAGE \
            --build-arg NEXT_PUBLIC_ENV_STATUS=$NEXT_PUBLIC_ENV_STATUS \
            --build-arg NEXT_PUBLIC_SUBDOMAIN_FOR_PRODUCTION=$NEXT_PUBLIC_SUBDOMAIN_FOR_PRODUCTION \
            --build-arg NEXT_PUBLIC_THOUGHTS_NUMBER_BY_LIST_PAGE=$NEXT_PUBLIC_THOUGHTS_NUMBER_BY_LIST_PAGE \
            --build-arg DATABASE_URL=$DATABASE_URL \
            --build-arg DIRECT_URL=$DIRECT_URL \
            .

      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$SERVICE_NAME:$GITHUB_SHA
          "$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA",

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$SERVICE_NAME:$GITHUB_SHA \
            --region $GCP_REGION \
            --platform managed \
            --allow-unauthenticated
